# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: zzhang88@u.rochester.edu
full_name: Mona
license: MIT
min_python_version: '3.9'
org: Mona
project_name: python-penguin
project_short_description: A great package.
python_name: python_penguin
typing: loose
url: https://github.com/Monana000
